### PR TITLE
Chatbot

### PR DESCRIPTION
**Pull request by Rabianzo**
Updated script for chatbot functionality

### CODE REVIEW

**Comment by Rabianzo** [comment]
Script for Chatbot functionality

**Comment by LundiLanga** [comment]
> Script for Chatbot functionality

It seems working fine on my side

**Comment by sidon59** [comment]
looks good

**Review by sidon59 — APPROVED** [review]

**Review by sidon59 — APPROVED** [review]

**Review by LundiLanga — APPROVED** [review]

**Review by LawSibisi — APPROVED** [review]
I have noticed that you updated your footer, looks fine by me.

**Review by LundiLanga — APPROVED** [review]

**Review by Sinethemba7vitsha — APPROVED** [review]
Changes made

**Review by sidon59 — APPROVED** [review]

**Review by sidon59 — APPROVED** [review]

**Review by LundiLanga — APPROVED** [review]

**Review by H3RT — APPROVED** [review]
Changes noted, approved.

**Review by sidon59 — APPROVED** [review]

**Pull request merged**
